FROM confluentinc/cp-server-connect:7.0.1
USER root
RUN mkdir -p /usr/share/java/confluentinc-kafka-connect-jdbc
ADD confluentinc-kafka-connect-jdbc  /usr/share/java/confluentinc-kafka-connect-jdbc
USER 1001
