apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7
  labels:
    app: centos7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos7
  template:
    metadata:
      labels:
        app: centos7
    spec:
      containers:
      - name: centos7
        image: quay.io/de_zhao_liu_ibm/tool:python3
        command: ["sleep"]
        args: ["9999999"]
#centos:centos7.9.2009
